#services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB='
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'


services:
  postgres-db:
    container_name: budgetDB
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: tracker
      POSTGRES_DB: budget
    ports:
      - "5436:5432"