CREATE TABLE budget_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category VARCHAR(255),
    created  TIMESTAMP WITHOUT TIME ZONE,
    amount   DOUBLE PRECISION,
    percent  INTEGER,
    CONSTRAINT pk_budget_items PRIMARY KEY (id)
);